let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme solarized
set relativenumber
set number
set tabstop=2
set shiftwidth=2
set softtabstop=2
set clipboard=unnamedplus
