" call plug#begin('~/.vim/plugged')
" Plug 'tpope/vim-sensible'
" Plug 'tpope/vim-surround'
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
" Plug 'ekalinin/Dockerfile.vim'
" Plug 'lifepillar/vim-solarized8'
" Plug 'christoomey/vim-tmux-navigator'
" Plug 'udalov/kotlin-vim'
" Plug 'jparise/vim-graphql'
" call plug#end()
" 
" set termguicolors
" let g:solarized_term_italics=0
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme solarized
" 
" let g:airline_theme='solarized'
" 
set relativenumber
set number
set tabstop=2       " The width of a TAB is set to 4.
                    " Still it is a \t. It is just that
                    " Vim will interpret it to be having
                    " a width of 4.

set shiftwidth=2    " Indents will have a width of 4

set softtabstop=2   " Sets the number of columns for a TAB
set clipboard=unnamedplus
