#!/run/current-system/sw/bin/bash
# logout dialog

cmd=$(echo -e "suspend\nlogout\nreboot\npoweroff" | rofi -width 350 -dmenu -p "> " )
case $cmd in
    suspend)
        systemctl suspend 
				;;
    logout)
			  i3-msg exit
				;;
    reboot)
        systemctl reboot 
				;;
    poweroff)
        systemctl poweroff 
				;;
esac
