# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "axios-0.19.0" = {
      name = "axios";
      packageName = "axios";
      version = "0.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.19.0.tgz";
        sha512 = "1uvKqKQta3KBxIz14F2v06AEHZ/dIoeKfbTRkK1E5oqjDnuEerLmYTgJB5AiQZHJcljpg1TuRzdjDR06qNk0DQ==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "diacritics-1.3.0" = {
      name = "diacritics";
      packageName = "diacritics";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/diacritics/-/diacritics-1.3.0.tgz";
        sha1 = "3efa87323ebb863e6696cebb0082d48ff3d6f7a1";
      };
    };
    "es-abstract-1.14.1" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.1.tgz";
        sha512 = "cp/Tb1oA/rh2X7vqeSOvM+TSo3UkJLX70eNihgVEvnzwAgikjkTFr/QVgRCaxjm0knCNQzNoxxxcw2zO2LJdZA==";
      };
    };
    "es-to-primitive-1.2.0" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.0.tgz";
        sha512 = "qZryBOJjV//LaxLTV6UC//WewneB3LcXOL9NP++ozKVXsIIIpm/2c13UDiD9Jp2eThsecw9m3jPqDwTyobcdbg==";
      };
    };
    "follow-redirects-1.5.10" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.5.10.tgz";
        sha512 = "0V5l4Cizzvqt5D44aTXbFZz+FtyXV1vrDN6qrelxtfYQKW0KO0W2T/hkE8xvGa/540LkZlkaUjO4ailYTFtHVQ==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-symbols-1.0.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.0.tgz";
        sha1 = "ba1a8f1af2a0fc39650f5c850367704122063b44";
      };
    };
    "is-buffer-2.0.3" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-2.0.3.tgz";
        sha512 = "U15Q7MXTuZlrbymiz95PJpZxu8IlipAp4dtS3wOdgPXx3mqBnslrWU14kxfHB+Py/+2PVKSr37dMAgM2A4uArw==";
      };
    };
    "is-callable-1.1.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.4.tgz";
        sha512 = "r5p9sxJjYnArLjObpjA4xu5EKI3CuKHkJXMhT7kwbpUyIFD1n5PMAsoPvWnvtZiNz7LjkYDRZhd7FlI0eMijEA==";
      };
    };
    "is-date-object-1.0.1" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.1.tgz";
        sha1 = "9aa20eb6aeebbff77fbd33e74ca01b33581d3a16";
      };
    };
    "is-regex-1.0.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.4.tgz";
        sha1 = "5517489b547091b0930e095654ced25ee97e9491";
      };
    };
    "is-symbol-1.0.2" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.2.tgz";
        sha512 = "HS8bZ9ox60yCJLH9snBpIwv9pYUAkcuLhSA1oero1UB5y9aiQpRA8y2ex945AOtCZL1lJDeIk3G5LthswI46Lw==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "node-hue-api-2.4.6" = {
      name = "node-hue-api";
      packageName = "node-hue-api";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-hue-api/-/node-hue-api-2.4.6.tgz";
        sha512 = "XeIejo9zJuyBo0c/0SjLz6yOqUEuUohEoiSEcwaXStzFVa/F001MeGg5idYK4gT3MBlXQ1tgdc/AfQB59djtVA==";
      };
    };
    "object-inspect-1.6.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.6.0.tgz";
        sha512 = "GJzfBZ6DgDAmnuaM3104jR4s1Myxr3Y3zfIyN4z3UdqN69oSRacNK8UhnobDdC+7J2AHCjGwxQubNJfE70SXXQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.getownpropertydescriptors-2.0.3" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.0.3.tgz";
        sha1 = "8758c846f5b407adab0f236e0986f14b051caa16";
      };
    };
    "q-1.4.1" = {
      name = "q";
      packageName = "q";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.4.1.tgz";
        sha1 = "55705bcd93c5f3673530c2c2cbc0c2b3addc286e";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "string.prototype.trimleft-2.0.0" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.0.0.tgz";
        sha1 = "68b6aa8e162c6a80e76e3a8a0c2e747186e271ff";
      };
    };
    "string.prototype.trimright-2.0.0" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.0.0.tgz";
        sha1 = "ab4a56d802a01fbe7293e11e84f24dc8164661dd";
      };
    };
    "traits-0.4.0" = {
      name = "traits";
      packageName = "traits";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/traits/-/traits-0.4.0.tgz";
        sha1 = "416edcabdc8bf64bd29102a7453dcddd857371a1";
      };
    };
    "util.promisify-1.0.0" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.0.tgz";
        sha512 = "i+6qA2MPhvoKLuxnJNpXAGhg7HphQOSUq2LKMZD0m15EiskXUkMvKdF4Uui0WYeCUGea+o2cw/ZuwehtfsrNkA==";
      };
    };
    "xml2js-0.4.22" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.22.tgz";
        sha512 = "MWTbxAQqclRSTnehWWe5nMKzI3VmJ8ltiJEco8akcC6j3miOhjjfzKum5sId+CWhfxdOs/1xauYr8/ZDBtQiRw==";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
  };
in
{
  "@sinedied/hue-cli" = nodeEnv.buildNodePackage {
    name = "_at_sinedied_slash_hue-cli";
    packageName = "@sinedied/hue-cli";
    version = "1.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@sinedied/hue-cli/-/hue-cli-1.1.0.tgz";
      sha1 = "cd20543997814983350afcb6897744457c01c4e9";
    };
    dependencies = [
      sources."axios-0.19.0"
      sources."debug-3.1.0"
      sources."deep-extend-0.6.0"
      sources."define-properties-1.1.3"
      sources."diacritics-1.3.0"
      sources."es-abstract-1.14.1"
      sources."es-to-primitive-1.2.0"
      sources."follow-redirects-1.5.10"
      sources."function-bind-1.1.1"
      sources."has-1.0.3"
      sources."has-symbols-1.0.0"
      sources."is-buffer-2.0.3"
      sources."is-callable-1.1.4"
      sources."is-date-object-1.0.1"
      sources."is-regex-1.0.4"
      sources."is-symbol-1.0.2"
      sources."minimist-1.2.0"
      sources."ms-2.0.0"
      sources."node-hue-api-2.4.6"
      sources."object-inspect-1.6.0"
      sources."object-keys-1.1.1"
      sources."object.getownpropertydescriptors-2.0.3"
      sources."q-1.4.1"
      sources."sax-1.2.4"
      sources."string.prototype.trimleft-2.0.0"
      sources."string.prototype.trimright-2.0.0"
      sources."traits-0.4.0"
      sources."util.promisify-1.0.0"
      sources."xml2js-0.4.22"
      sources."xmlbuilder-11.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Simple command line interface for Philips Hue";
      homepage = https://github.com/sinedied/hue-cli;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}