# COMPLETION
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 2 numeric
zstyle ':completion:*' prompt '%e'
zstyle ':completion:*' substitute 1


# enable completion menu
zstyle ':completion:*' menu select

# for all completions: grouping the output
zstyle ':completion:*' group-name ''

# for all completions: show comments when present
zstyle ':completion:*' verbose yes
zstyle :compinstall filename '~/.zshrc'


# COLORS

autoload -U colors && colors

ZSH_LS_COLORS="$LS_COLORS"
zstyle ':completion:*' list-colors "${(@s.:.)ZSH_LS_COLORS}"

# for all completions: grouping / headline / ...
zstyle ':completion:*:messages' format $'\e[01;35m -- %d -- \e[00;00m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found -- \e[00;00m'
zstyle ':completion:*:descriptions' format $'\e[01;34m -- %d -- \e[00;00m'
zstyle ':completion:*:corrections' format $'\e[01;35m -- %d -- \e[00;00m'

# statusline for many hits
zstyle ':completion:*:default' select-prompt $'\e[01;35m -- Match %M    %P -- \e[00;00m'

function ema(){
    xrandr  --output DP-1 --right-of eDP-1 --auto
    # scaling degrades performance
    # TODO find a workaround for this
    # xrandr --output DP-1 --mode 3840x2160 --right-of eDP-1 --scale 0.75x0.75 --rate 25.00

    sleep 1

    ddcutil setvcp 10 100 --display 1
    polybar external & disown
    nitrogen --restore

    sleep 1
    xinput map-to-output 17 DP-1
}

function emd(){
    pkill -f "polybar external"
    xrandr --output DP-1 --off
}

# PROMPT

# remove default indicator
RPS1=''

# ZAW
# https://github.com/zsh-users/zaw

zstyle ':filter-select' hist-find-no-dups yes # ignore duplicates in history source
zstyle ':filter-select' max-lines 10 # use 10 lines for filter-select
zstyle ':filter-select:highlight' title fg=brightblue,standout
zstyle ':filter-select:highlight' makked fg=brightred,standout
zstyle ':filter-select:highlight' matched fg=cyan,standout
zstyle ':filter-select:highlight' selected fg=yellow,standout
zstyle ':filter-select:highlight' error fg=red,standout

# unbind execute-command from vicmd (not using it)
bindkey -r -M vicmd ' '
bindkey -r -M vicmd ':'

# bind some with space as leader
bindkey -M vicmd ' h' zaw-history
bindkey -M vicmd ' p' zaw-process
bindkey -M filterselect '^[' send-break


# set cursor color
echo -ne "\e]12;#00FF00\a"
